name: Run tests and upload coverage

on: 
  push

jobs:
  test:
    name: Run tests and collect coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Set up Node
        uses: actions/setup-node@v4

      - name: Install dependencies
        run: npm install
        working-directory: my-app

      - name: Run tests
        run: npx vitest run --coverage
        working-directory: my-app
        continue-on-error: true   # 👈 still generate coverage even if tests fail

      - name: Upload results to Codecov
        if: always()              # 👈 run even if previous step fails
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./my-app/coverage/*.json # adjust if vitest outputs elsewhere
